Rebuild our dev-env container on merge
openSUSE/kurren pull request #19
Opened 2022-04-04 13:19 UTC by hennevogel

So far we are using a `Token::Service`

2022-04-04 19:37 UTC, dmarcoux approved these changes

2022-04-04 19:38 UTC, dmarcoux requested changes

2022-04-04 19:38 UTC, dmarcoux commented on .obs/workflows.yml
> +        - master
```suggestion
        - main
```

2022-04-05 14:00 UTC, hennevogel commented on .obs/workflows.yml
> +        - master
fixed...

2022-04-05 15:07 UTC, dmarcoux approved these changes

2022-04-06 13:23 UTC, merged